version: "3"

services:
  auth-db:
    image: postgres:latest
    container_name: auth-db
    environment:
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_NON_ROOT_USER=postgres"
      - "POSTGRES_NON_ROOT_USER_PASSWORD=postgres"
      - "AUTH_DATABASE_NAME=keycloak"
      - "AUTH_DATABASE_USER=keycloak"
      - "AUTH_DATABASE_PASSWORD=keycloak"
    ports:
      - "15432:15432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/initdb:/docker-entrypoint-initdb.d

  auth-server:
    image: majidhajric/auth-server:latest
    container_name: auth-server
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=9090
    ports:
      - "9090:9090"
    environment:
      - "PORT=9090"
      - "KEYCLOAK_USER=keycloak"
      - "KEYCLOAK_PASSWORD=keycloak"
      - "DB_VENDOR=POSTGRES"
      - "DB_ADDR=auth-db"
      - "DB_PORT=15432"
      - "DB_DATABASE=keycloak"
      - "DB_USER=keycloak"
      - "DB_PASSWORD=keycloak"
      - "PROXY_ADDRESS_FORWARDING=true"
    depends_on:
      - auth-db
